Updated to use Font Awesome 6
posquit0/Awesome-CV pull request #418
Opened 2022-03-25 23:32 UTC by xaviermawet

Hi,

This pull request adds latex commands for **Font Awesome 6.1.1** free icons (inspired by #258 and #235).

Since there is no official FontAwesome6 package yet, I created a node application ([latex-fontawesome](https://github.com/xaviermawet/latex-fontawesome/tree/develop)) that consumes the [Font Awesome GraphQL API](https://fontawesome.com/docs/apis/graphql/get-started) to get icons metadata and generate definitions (`sty` file). Logic is based on [plorcupine's latex-fontawesome](https://github.com/plorcupine/latex-fontawesome) project.

Steps in order to use icons from so-generated `fontawesome6.sty` file:
1. Use search on the official [website](https://fontawesome.com/icons?d=gallery) to find icon by name or related tags.
2. Use unicode of the desired icon to search for latex definition in `fontawesome6.sty`.
3. Copy and paste the associated definition in your latex document.

2022-03-26 01:45 UTC, OJFord commented
I've only quickly skimmed, but based on that the bot's comment seems unreasonable! Thanks for the PR, will look properly shortly.

2022-04-13 18:17 UTC, OJFord requested changes
I'm certainly in favour of keeping the dependency up to date, but I'm not sure how I feel about bundling it rather than using a version published on CTAN.

Have you considered publishing yours?

2022-04-13 18:17 UTC, OJFord commented on awesome-cv.cls
> +          \href{tel:\@mobile}{\faPhone\acvHeaderIconSep\@mobile}%
Does `faMobile` still exist in FA6?

If so, please leave it as it is, it's sort of a 'breaking change' to change the icon under people's feet, and may be a surprise to some/not wanted by everyone. There's some discussion of making it easier to 'override' icons (i.e. you could use `faPhone` if that's your preference) in #420.

2022-04-13 18:17 UTC, OJFord commented on awesome-cv.cls
> +          \href{mailto:\@email}{\faEnvelopeOpenText\acvHeaderIconSep\@email}%
Ditto `faEnvelope`?

2022-04-13 18:17 UTC, OJFord commented on awesome-cv.cls
> +          \mbox{\faCakeCandles\acvHeaderIconSep\@dateofbirth}%
This one I gather is just a name change?

2022-04-13 18:17 UTC, OJFord commented on awesome-cv.cls
> +          \href{http://\@homepage}{\faArrowPointer\acvHeaderIconSep\@homepage}%
Ditto `faHome`

2022-04-13 18:17 UTC, OJFord commented on awesome-cv.cls
> +          \href{https://github.com/\@github}{\faGithub\acvHeaderIconSep\@github}%
Ditto `faGithubSquare`

2022-04-14 20:37 UTC, xaviermawet commented on awesome-cv.cls
> +          \href{tel:\@mobile}{\faPhone\acvHeaderIconSep\@mobile}%
Yes `faMobile` still exists. I took advantage of my PR to change some icons for others more relevant from my point of view. However, I fully understand that changing the icons can be confusing for those using the template as is.
I will restore the same icons as the old ones

2022-04-14 20:44 UTC, xaviermawet commented on awesome-cv.cls
> +          \href{mailto:\@email}{\faEnvelopeOpenText\acvHeaderIconSep\@email}%
Yes `faEnvelope` still exists in Font Awesome 6. However, there are now two variations of the envelope in the free part of font awesome 6: **solid** and **regular**. So, to keep the same icon, the new command is `\faEnvelopeS`

2022-04-14 20:46 UTC, xaviermawet commented on awesome-cv.cls
> +          \mbox{\faCakeCandles\acvHeaderIconSep\@dateofbirth}%
Yes, just a name change, but same icon

2022-04-14 20:49 UTC, xaviermawet commented on awesome-cv.cls
> +          \href{http://\@homepage}{\faArrowPointer\acvHeaderIconSep\@homepage}%
Yes, this icon still exists under another name `faHouseChimney`. I'll restore it

2022-04-14 21:00 UTC, xaviermawet commented
> I'm certainly in favour of keeping the dependency up to date, but I'm not sure how I feel about bundling it rather than using a version published on CTAN.
> 
> Have you considered publishing yours?

I've never created or published a package on CTAN. I'm gonna try to do it and thus update my PR

2022-04-14 21:02 UTC, xaviermawet commented on awesome-cv.cls
> +          \href{https://github.com/\@github}{\faGithub\acvHeaderIconSep\@github}%
I'll restore the previous icon

2022-04-14 21:34 UTC, OJFord commented on awesome-cv.cls
> +          \href{tel:\@mobile}{\faPhone\acvHeaderIconSep\@mobile}%
Thanks

2022-07-14 16:25 UTC, OJFord commented
Any luck with CTAN @xaviermawet?

2022-07-21 20:45 UTC, xaviermawet commented
Hi @OJFord, I'll look into it very soon but with work and family, I haven't found the time to do it yet.
I also contacted Marcel Fabian Krüger, author of the fontawesome5 package, and he told me he had no plan to create a
fontawesome6 package.
I keep you informed in the coming weeks

2022-07-21 21:23 UTC, OJFord commented
Of course, no problem, just noticed you added some commits do wondered if you'd managed it.

Cheers

2022-08-05 14:39 UTC, willb256 commented
I planned on opening a pull request for this but then I realized there's already one opened. Why not just remove (or comment on) \RequirePackage{fontawesome} in awesome-cv.cls and add a new package using \usepackage{fontawesome5}? It's not Font Awesome 6 but at least it's more updated compared to the original package.

2022-08-16 23:04 UTC, xaviermawet commented
I uploaded un a package named fontawesome6 on CTAN. I'm waiting for validation

2022-08-19 11:59 UTC, OJFord commented
Oh great, nice one 🙂

2022-08-26 02:57 UTC, willb256 commented
@xaviermawet I can't find the package on CTAN

2022-08-26 05:54 UTC, xaviermawet commented
@willb256 the package hasn't been validated yet. I'm currently discussing with one CTAN's validator and the authors of others fontawesome packages to synchronize us about the package naming vs fontawesome version, the macros collision with other fontawesome packages, etc... So my package isn't available yet because it didn't pass the validation phase right now. But it should be available soon. Stay tune !

2023-01-04 15:45 UTC, Loco169976 commented
🥺

2023-11-29 00:20 UTC, OJFord commented
This bot seems a bit annoying @posquit0, I'm not sure we get enough (genuine) PRs that we can't make that judgement 'manually' - any objection to turning it off? Or at least only running on PR creation, not every update (which can get very noisy as here).

2023-12-01 13:22 UTC, posquit0 commented
For now, I've excluded the binary files and the examples directory for `pull-request-labler` action. I don't think this will solve the problem, so I'll look into something else soon.

2025-05-05 22:26 UTC, xaviermawet commented
This is probably the longest-lived PR I've ever opened: 3 years, 1 month, and 10 days 🤣 !

I honestly thought this day might never come — but it finally did: a [fontawesome6](https://ctan.org/pkg/fontawesome6) package has been published on CTAN! And I haven’t forgotten about this PR either, so I’ve taken the liberty to update it accordingly.

If `fontawesome6` isn’t yet available in your LaTeX distribution, you can either 
- manually update your packages
```bash
tlmgr update --self --all
```
- or use the installation script ([`local_install.sh`](https://github.com/braniii/fontawesome/blob/main/local_install.sh)) provided in the author’s repository.

2025-05-13 21:59 UTC, xaviermawet commented
The `texlive/texlive:latest` docker image has been updated and now contains the package `fontawesome6` this PR can be validated 👍🏻

2025-05-14 08:41 UTC, OJFord commented
Amazing, thanks @xaviermawet! I'll just double-check it against mine this evening, but all being well good to go I think, appreciate your work on this 🙂

2025-06-15 21:41 UTC, xaviermawet commented
Any chance for a merge 😇 ?

2025-06-25 22:17 UTC, OJFord commented
@xaviermawet Thanks again so much for your work on this, I just wanted to do my due diligence/sanity check with my own CV; I finally got around to it this evening, and it LGTM!

(I do see a new issue.. but I don't believe it's caused by this, and the FA icons are working fine.)



Thanks!

2025-06-25 22:18 UTC, merged